language: python

python:
   - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install coveralls
 - pip install pytest pytest-cov

before_install:
 - git clone https://github.com/Njaya2019/storemanager-endpoints/tree/developer
 - cd storemanager-endpoints 
 
script:
 - pytest --cov=.

after_success:
 - coveralls
